"""empty message

Revision ID: 945b71997bce
Revises: b5850b6295da
Create Date: 2020-02-22 00:58:20.506812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945b71997bce'
down_revision = 'b5850b6295da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
